apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: um238n15g-python
  janus-idp.io/tekton: um238n15g-python
  backstage.io/kubernetes-id: um238n15g-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: um238n15g-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
