apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: um238n15g-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: um238n15g-python 
  name: um238n15g-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: um238n15g-python 
